"""Abstract interface for bank account persistence.

Defines the contract that all concrete account repository implementations
must fulfil.  Services depend ONLY on this interface, never on Cosmos SDK
directly (Dependency Inversion Principle).
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Optional


class IAccountRepository(ABC):
    """Abstract repository interface for BankAccount persistence.

    All methods are async to support non-blocking I/O with Cosmos DB.
    The concrete implementation is generated by cosmosdb-repo-agent.
    """

    @abstractmethod
    async def create(self, document: dict) -> dict:
        """Persist a new bank account document and return it.

        Args:
            document: Fully-formed account dict ready for storage.

        Returns:
            The persisted document as returned by the data store.
        """

    @abstractmethod
    async def get_by_account_number(self, account_number: str) -> Optional[dict]:
        """Retrieve a bank account by its unique account number.

        Args:
            account_number: The 10-digit account number (partition key).

        Returns:
            Account document dict, or None if not found.
        """

    @abstractmethod
    async def list_by_owner(
        self, owner_id: str, *, include_closed: bool = False
    ) -> list[dict]:
        """List all accounts belonging to a specific owner.

        Args:
            owner_id: The JWT sub of the account owner.
            include_closed: When True, also return CLOSED accounts.

        Returns:
            List of account dicts (empty list if none).
        """

    @abstractmethod
    async def list_all(self, *, include_closed: bool = True) -> list[dict]:
        """List all accounts in the system (admin use only).

        Args:
            include_closed: When False, exclude soft-deleted accounts.

        Returns:
            List of all account dicts.
        """

    @abstractmethod
    async def update(self, account_number: str, updates: dict) -> dict:
        """Apply a partial update to an existing bank account.

        Args:
            account_number: The 10-digit account number.
            updates: Dict of fields to patch.

        Returns:
            The updated document.
        """
