"""Abstract interface for user profile persistence.

Defines the contract that all concrete user profile repository
implementations must fulfil.  Services depend ONLY on this interface,
never on Cosmos SDK directly (Dependency Inversion Principle).
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Optional


class IUserProfileRepository(ABC):
    """Abstract repository interface for UserProfile persistence.

    All methods are async to support non-blocking I/O with Cosmos DB.
    The concrete implementation is generated by cosmosdb-repo-agent.
    """

    @abstractmethod
    async def get_by_owner_id(self, owner_id: str) -> Optional[dict]:
        """Retrieve a user profile document by owner ID.

        Args:
            owner_id: The JWT sub of the profile owner (partition key).

        Returns:
            Profile document dict, or None if not found.
        """

    @abstractmethod
    async def upsert(self, document: dict) -> dict:
        """Create or replace a user profile document.

        If a document with the same owner_id already exists it is replaced
        in full; otherwise a new document is created.

        Args:
            document: Fully-formed profile dict ready for storage.

        Returns:
            The persisted document as returned by the data store.
        """
