name: CI

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - '.pipelines/variables/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build, test, and publish image
    uses: ./.github/workflows/workflow-build-v1.0.0.yml
    with:
      python_version: '3.11'
      working_directory: '.'
      release_environment: dev
      container_registry_url: ${{ vars.ACR_LOGIN_SERVER_DEV }}
      container_image_repository: 'banking-system/fastapi-azure-app'
      generate_sbom: true
      sign_image: false
    secrets:
      registry_username: ${{ secrets.ACR_USERNAME }}
      registry_password: ${{ secrets.ACR_PASSWORD }}
