name: PR Validation

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - '.pipelines/variables/**'

permissions:
  contents: read

jobs:
  pr-validation:
    name: Validate Python source
    uses: sachin-khiladi/devops-templates/templates/github/python/workflow-build-v1.0.0.yml@v1.0
    with:
      python_version: '3.11'
      working_directory: '.'
      release_environment: dev
